/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Supported Operating system details.
 *
 */
class SupportedOSDetails {
  /**
   * Create a SupportedOSDetails.
   * @property {string} [osName] The name.
   * @property {string} [osType] The type.
   * @property {array} [osVersions] List of version for OS.
   */
  constructor() {
  }

  /**
   * Defines the metadata of SupportedOSDetails
   *
   * @returns {object} metadata of SupportedOSDetails
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SupportedOSDetails',
      type: {
        name: 'Composite',
        className: 'SupportedOSDetails',
        modelProperties: {
          osName: {
            required: false,
            serializedName: 'osName',
            type: {
              name: 'String'
            }
          },
          osType: {
            required: false,
            serializedName: 'osType',
            type: {
              name: 'String'
            }
          },
          osVersions: {
            required: false,
            serializedName: 'osVersions',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'OSVersionWrapperElementType',
                  type: {
                    name: 'Composite',
                    className: 'OSVersionWrapper'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = SupportedOSDetails;
