/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 * 
 * Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the USqlAssemblyClr class.
 * @constructor
 * A Data Lake Analytics catalog U-SQL assembly CLR item.
 * @member {string} [databaseName] Gets or sets the name of the database.
 * 
 * @member {string} [assemblyClrName] Gets or sets the name of the assembly.
 * 
 * @member {string} [clrName] Gets or sets the name of the CLR.
 * 
 * @member {string} [computeAccountName] Gets or sets the name of the Data
 * Lake Analytics account.
 * 
 * @member {string} [version] Gets or sets the version of the catalog item.
 * 
 */
function USqlAssemblyClr(parameters) {
  if (parameters !== null && parameters !== undefined) {
    if (parameters.databaseName !== undefined) {
      this.databaseName = parameters.databaseName;
    }
    if (parameters.assemblyClrName !== undefined) {
      this.assemblyClrName = parameters.assemblyClrName;
    }
    if (parameters.clrName !== undefined) {
      this.clrName = parameters.clrName;
    }
    if (parameters.computeAccountName !== undefined) {
      this.computeAccountName = parameters.computeAccountName;
    }
    if (parameters.version !== undefined) {
      this.version = parameters.version;
    }
  }    
}


/**
 * Validate the payload against the USqlAssemblyClr schema
 *
 * @param {JSON} payload
 *
 */
USqlAssemblyClr.prototype.serialize = function () {
  var payload = {};
  if (this['databaseName'] !== null && this['databaseName'] !== undefined) {
    if (typeof this['databaseName'].valueOf() !== 'string') {
      throw new Error('this[\'databaseName\'] must be of type string.');
    }
    payload['databaseName'] = this['databaseName'];
  }

  if (this['assemblyClrName'] !== null && this['assemblyClrName'] !== undefined) {
    if (typeof this['assemblyClrName'].valueOf() !== 'string') {
      throw new Error('this[\'assemblyClrName\'] must be of type string.');
    }
    payload['assemblyClrName'] = this['assemblyClrName'];
  }

  if (this['clrName'] !== null && this['clrName'] !== undefined) {
    if (typeof this['clrName'].valueOf() !== 'string') {
      throw new Error('this[\'clrName\'] must be of type string.');
    }
    payload['clrName'] = this['clrName'];
  }

  if (this['computeAccountName'] !== null && this['computeAccountName'] !== undefined) {
    if (typeof this['computeAccountName'].valueOf() !== 'string') {
      throw new Error('this[\'computeAccountName\'] must be of type string.');
    }
    payload['computeAccountName'] = this['computeAccountName'];
  }

  if (this['version'] !== null && this['version'] !== undefined) {
    if (typeof this['version'].valueOf() !== 'string') {
      throw new Error('this[\'version\'] must be of type string.');
    }
    payload['version'] = this['version'];
  }

  return payload;
};

/**
 * Deserialize the instance to USqlAssemblyClr schema
 *
 * @param {JSON} instance
 *
 */
USqlAssemblyClr.prototype.deserialize = function (instance) {
  if (instance) {
    if (instance['databaseName'] !== undefined) {
      this['databaseName'] = instance['databaseName'];
    }

    if (instance['assemblyClrName'] !== undefined) {
      this['assemblyClrName'] = instance['assemblyClrName'];
    }

    if (instance['clrName'] !== undefined) {
      this['clrName'] = instance['clrName'];
    }

    if (instance['computeAccountName'] !== undefined) {
      this['computeAccountName'] = instance['computeAccountName'];
    }

    if (instance['version'] !== undefined) {
      this['version'] = instance['version'];
    }
  }

  return this;
};

module.exports = USqlAssemblyClr;
