/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Response for the CheckDnsNameAvailability API service call.
 *
 */
class DnsNameAvailabilityResult {
  /**
   * Create a DnsNameAvailabilityResult.
   * @member {boolean} [available] Domain availability (True/False).
   */
  constructor() {
  }

  /**
   * Defines the metadata of DnsNameAvailabilityResult
   *
   * @returns {object} metadata of DnsNameAvailabilityResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'DnsNameAvailabilityResult',
      type: {
        name: 'Composite',
        className: 'DnsNameAvailabilityResult',
        modelProperties: {
          available: {
            required: false,
            serializedName: 'available',
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = DnsNameAvailabilityResult;
