/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 * 
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

var util = require('util');

/**
 * @class
 * Initializes a new instance of the RuleWebhookAction class.
 * @constructor
 * Specifies the action to post to service when the rule condition is
 * evaluated.
 *
 * @member {string} [serviceUri] the service uri to Post the notitication.
 * 
 * @member {object} [properties] the dictionary of custom properties to
 * include with the post operation.
 * 
 */
function RuleWebhookAction() {
  RuleWebhookAction['super_'].call(this);
}

util.inherits(RuleWebhookAction, models['RuleAction']);

/**
 * Defines the metadata of RuleWebhookAction
 *
 * @returns {object} metadata of RuleWebhookAction
 *
 */
RuleWebhookAction.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'Microsoft.Azure.Management.Insights.Models.RuleWebhookAction',
    type: {
      name: 'Composite',
      className: 'RuleWebhookAction',
      modelProperties: {
        odatatype: {
          required: true,
          serializedName: 'odata\\.type',
          type: {
            name: 'String'
          }
        },
        serviceUri: {
          required: false,
          serializedName: 'serviceUri',
          type: {
            name: 'String'
          }
        },
        properties: {
          required: false,
          serializedName: 'properties',
          type: {
            name: 'Dictionary',
            value: {
                required: false,
                serializedName: 'StringElementType',
                type: {
                  name: 'String'
                }
            }
          }
        }
      }
    }
  };
};

module.exports = RuleWebhookAction;
