/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a PredictionQueryResult.
 */
class PredictionQueryResult {
  /**
   * Create a PredictionQueryResult.
   * @member {object} [token]
   * @member {string} [token.session]
   * @member {string} [token.continuation]
   * @member {number} [token.maxCount]
   * @member {string} [token.orderBy] Possible values include: 'Newest',
   * 'Oldest', 'Suggested'
   * @member {array} [token.tags]
   * @member {uuid} [token.iterationId]
   * @member {date} [token.startTime]
   * @member {date} [token.endTime]
   * @member {string} [token.application]
   * @member {array} [results]
   */
  constructor() {
  }

  /**
   * Defines the metadata of PredictionQueryResult
   *
   * @returns {object} metadata of PredictionQueryResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'PredictionQueryResult',
      type: {
        name: 'Composite',
        className: 'PredictionQueryResult',
        modelProperties: {
          token: {
            required: false,
            readOnly: true,
            serializedName: 'token',
            type: {
              name: 'Composite',
              className: 'PredictionQueryToken'
            }
          },
          results: {
            required: false,
            nullable: true,
            readOnly: true,
            serializedName: 'results',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StoredImagePredictionElementType',
                  type: {
                    name: 'Composite',
                    className: 'StoredImagePrediction'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = PredictionQueryResult;
