/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.ResponseBase = require('./responseBase');
exports.Identifiable = require('./identifiable');
exports.Response = require('./response');
exports.Thing = require('./thing');
exports.CreativeWork = require('./creativeWork');
exports.Article = require('./article');
exports.NewsArticle = require('./newsArticle');
exports.Answer = require('./answer');
exports.SearchResultsAnswer = require('./searchResultsAnswer');
exports.News = require('./news');
exports.MediaObject = require('./mediaObject');
exports.ImageObject = require('./imageObject');
exports.Query = require('./query');
exports.NewsTopic = require('./newsTopic');
exports.TrendingTopics = require('./trendingTopics');
exports.VideoObject = require('./videoObject');
exports.Organization = require('./organization');
exports.ErrorModel = require('./errorModel');
exports.ErrorResponse = require('./errorResponse');
exports.discriminators = {
  'ResponseBase.NewsArticle' : exports.NewsArticle,
  'ResponseBase.News' : exports.News,
  'ResponseBase.SearchResultsAnswer' : exports.SearchResultsAnswer,
  'ResponseBase.ImageObject' : exports.ImageObject,
  'ResponseBase.News/Topic' : exports.NewsTopic,
  'ResponseBase.Answer' : exports.Answer,
  'ResponseBase.Article' : exports.Article,
  'ResponseBase.Thing' : exports.Thing,
  'ResponseBase.Response' : exports.Response,
  'ResponseBase.TrendingTopics' : exports.TrendingTopics,
  'ResponseBase.VideoObject' : exports.VideoObject,
  'ResponseBase.CreativeWork' : exports.CreativeWork,
  'ResponseBase.Organization' : exports.Organization,
  'ResponseBase.Identifiable' : exports.Identifiable,
  'ResponseBase.ErrorResponse' : exports.ErrorResponse,
  'ResponseBase.MediaObject' : exports.MediaObject,
  'ResponseBase' : exports.ResponseBase
};
