/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the NameValuePair class.
 * @constructor
 * Name value pair.
 *
 * @member {string} [name] Pair name.
 *
 * @member {string} [value] Pair value.
 *
 */
class NameValuePair {
  constructor() {
  }

  /**
   * Defines the metadata of NameValuePair
   *
   * @returns {object} metadata of NameValuePair
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'NameValuePair',
      type: {
        name: 'Composite',
        className: 'NameValuePair',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          value: {
            required: false,
            serializedName: 'value',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = NameValuePair;
