/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Properties of the disk to detach.
 *
 */
class DetachDiskProperties {
  /**
   * Create a DetachDiskProperties.
   * @member {string} [leasedByLabVmId] The resource ID of the Lab VM to which
   * the disk is attached.
   */
  constructor() {
  }

  /**
   * Defines the metadata of DetachDiskProperties
   *
   * @returns {object} metadata of DetachDiskProperties
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'DetachDiskProperties',
      type: {
        name: 'Composite',
        className: 'DetachDiskProperties',
        modelProperties: {
          leasedByLabVmId: {
            required: false,
            serializedName: 'leasedByLabVmId',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = DetachDiskProperties;
