/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Azure Storage account list information.
 */
class StorageAccountInformationListResult extends Array {
  /**
   * Create a StorageAccountInformationListResult.
   * @member {string} [nextLink] The link (url) to the next page of results.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of StorageAccountInformationListResult
   *
   * @returns {object} metadata of StorageAccountInformationListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'StorageAccountInformationListResult',
      type: {
        name: 'Composite',
        className: 'StorageAccountInformationListResult',
        modelProperties: {
          value: {
            required: false,
            readOnly: true,
            serializedName: '',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StorageAccountInformationElementType',
                  type: {
                    name: 'Composite',
                    className: 'StorageAccountInformation'
                  }
              }
            }
          },
          nextLink: {
            required: false,
            readOnly: true,
            serializedName: 'nextLink',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = StorageAccountInformationListResult;
