/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the ApplicationUpgradeDeployedApplicationHealthStates class.
 * @constructor
 * @member {string} [domainName]
 * 
 * @member {string} [nodeUpgradeProgressList]
 * 
 */
function ApplicationUpgradeDeployedApplicationHealthStates() {
}

/**
 * Defines the metadata of ApplicationUpgradeDeployedApplicationHealthStates
 *
 * @returns {object} metadata of ApplicationUpgradeDeployedApplicationHealthStates
 *
 */
ApplicationUpgradeDeployedApplicationHealthStates.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'ApplicationUpgrade_DeployedApplicationHealthStates',
    type: {
      name: 'Composite',
      className: 'ApplicationUpgradeDeployedApplicationHealthStates',
      modelProperties: {
        domainName: {
          required: false,
          serializedName: 'DomainName',
          type: {
            name: 'String'
          }
        },
        nodeUpgradeProgressList: {
          required: false,
          serializedName: 'NodeUpgradeProgressList',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = ApplicationUpgradeDeployedApplicationHealthStates;
