/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

var util = require('util');

/**
 * @class
 * Initializes a new instance of the ApplicationHealthEvaluation class.
 * @constructor
 * The evaluation of the application health
 * @member {string} [serviceName]
 * 
 * @member {array} [unhealthyEvaluations]
 * 
 */
function ApplicationHealthEvaluation() {
  ApplicationHealthEvaluation['super_'].call(this);
}

util.inherits(ApplicationHealthEvaluation, models['HealthEvaluation']);

/**
 * Defines the metadata of ApplicationHealthEvaluation
 *
 * @returns {object} metadata of ApplicationHealthEvaluation
 *
 */
ApplicationHealthEvaluation.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'Application',
    type: {
      name: 'Composite',
      className: 'ApplicationHealthEvaluation',
      modelProperties: {
        description: {
          required: false,
          serializedName: 'Description',
          type: {
            name: 'String'
          }
        },
        aggregatedHealthState: {
          required: false,
          serializedName: 'AggregatedHealthState',
          type: {
            name: 'String'
          }
        },
        Kind: {
          required: true,
          serializedName: 'Kind',
          type: {
            name: 'String'
          }
        },
        serviceName: {
          required: false,
          serializedName: 'ServiceName',
          type: {
            name: 'String'
          }
        },
        unhealthyEvaluations: {
          required: false,
          serializedName: 'UnhealthyEvaluations',
          type: {
            name: 'Sequence',
            element: {
                required: false,
                serializedName: 'UnhealthyEvaluationElementType',
                type: {
                  name: 'Composite',
                  className: 'UnhealthyEvaluation'
                }
            }
          }
        }
      }
    }
  };
};

module.exports = ApplicationHealthEvaluation;
