/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the RoleDefinitionFilter class.
 * @constructor
 * Role Definitions filter
 *
 * @member {string} [roleName] Returns role definition with the specific name.
 *
 */
class RoleDefinitionFilter {
  constructor() {
  }

  /**
   * Defines the metadata of RoleDefinitionFilter
   *
   * @returns {object} metadata of RoleDefinitionFilter
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'RoleDefinitionFilter',
      type: {
        name: 'Composite',
        className: 'RoleDefinitionFilter',
        modelProperties: {
          roleName: {
            required: false,
            serializedName: 'roleName',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = RoleDefinitionFilter;
