/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @summary The TaskSlot counts for a Job.
  *
 */
class TaskSlotCounts {
  /**
   * Create a TaskSlotCounts.
   * @property {number} active The number of TaskSlots for active Tasks.
   * @property {number} running The number of TaskSlots for running Tasks.
   * @property {number} completed The number of TaskSlots for completed Tasks.
   * @property {number} succeeded The number of TaskSlots for succeeded Tasks.
   * @property {number} failed The number of TaskSlots for failed Tasks.
   */
  constructor() {
  }

  /**
   * Defines the metadata of TaskSlotCounts
   *
   * @returns {object} metadata of TaskSlotCounts
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'TaskSlotCounts',
      type: {
        name: 'Composite',
        className: 'TaskSlotCounts',
        modelProperties: {
          active: {
            required: true,
            serializedName: 'active',
            type: {
              name: 'Number'
            }
          },
          running: {
            required: true,
            serializedName: 'running',
            type: {
              name: 'Number'
            }
          },
          completed: {
            required: true,
            serializedName: 'completed',
            type: {
              name: 'Number'
            }
          },
          succeeded: {
            required: true,
            serializedName: 'succeeded',
            type: {
              name: 'Number'
            }
          },
          failed: {
            required: true,
            serializedName: 'failed',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = TaskSlotCounts;
