/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The network adapter position.
 *
 */
class NetworkAdapterPosition {
  /**
   * Create a NetworkAdapterPosition.
   * @property {string} [networkGroup] The network group. Possible values
   * include: 'None', 'NonRDMA', 'RDMA'
   * @property {number} [port] The port.
   */
  constructor() {
  }

  /**
   * Defines the metadata of NetworkAdapterPosition
   *
   * @returns {object} metadata of NetworkAdapterPosition
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'NetworkAdapterPosition',
      type: {
        name: 'Composite',
        className: 'NetworkAdapterPosition',
        modelProperties: {
          networkGroup: {
            required: false,
            readOnly: true,
            serializedName: 'networkGroup',
            type: {
              name: 'String'
            }
          },
          port: {
            required: false,
            readOnly: true,
            serializedName: 'port',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = NetworkAdapterPosition;
