/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Defines a managed rule group override setting.
 *
 */
class ManagedRuleOverride {
  /**
   * Create a ManagedRuleOverride.
   * @property {string} ruleId Identifier for the managed rule.
   * @property {string} [enabledState] Describes if the managed rule is in
   * enabled or disabled state. Defaults to Disabled if not specified. Possible
   * values include: 'Disabled', 'Enabled'
   * @property {string} [action] Describes the override action to be applied
   * when rule matches. Possible values include: 'Allow', 'Block', 'Log',
   * 'Redirect'
   */
  constructor() {
  }

  /**
   * Defines the metadata of ManagedRuleOverride
   *
   * @returns {object} metadata of ManagedRuleOverride
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ManagedRuleOverride',
      type: {
        name: 'Composite',
        className: 'ManagedRuleOverride',
        modelProperties: {
          ruleId: {
            required: true,
            serializedName: 'ruleId',
            type: {
              name: 'String'
            }
          },
          enabledState: {
            required: false,
            serializedName: 'enabledState',
            type: {
              name: 'String'
            }
          },
          action: {
            required: false,
            serializedName: 'action',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ManagedRuleOverride;
