/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the AndroidMAMPolicyCollection class.
 * @constructor
 * @member {string} [nextlink] Gets the URL to get the next set of results.
 *
 */
class AndroidMAMPolicyCollection extends Array {
  constructor() {
    super();
  }

  /**
   * Defines the metadata of AndroidMAMPolicyCollection
   *
   * @returns {object} metadata of AndroidMAMPolicyCollection
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'AndroidMAMPolicyCollection',
      type: {
        name: 'Composite',
        className: 'AndroidMAMPolicyCollection',
        modelProperties: {
          value: {
            required: true,
            serializedName: '',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'AndroidMAMPolicyElementType',
                  type: {
                    name: 'Composite',
                    className: 'AndroidMAMPolicy'
                  }
              }
            }
          },
          nextlink: {
            required: false,
            readOnly: true,
            serializedName: 'nextlink',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = AndroidMAMPolicyCollection;
