/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Result of the GetFaceList operation.
 *
 */
class GetFaceListResult {
  /**
   * Create a GetFaceListResult.
   * @member {string} faceListId faceListId of the target face list.
   * @member {string} [name] Face list's display name.
   * @member {string} [userData] User-provided data attached to this face list.
   * @member {array} [persistedFaces] Persisted faces within the face list.
   */
  constructor() {
  }

  /**
   * Defines the metadata of GetFaceListResult
   *
   * @returns {object} metadata of GetFaceListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'GetFaceListResult',
      type: {
        name: 'Composite',
        className: 'GetFaceListResult',
        modelProperties: {
          faceListId: {
            required: true,
            serializedName: 'faceListId',
            constraints: {
              MaxLength: 64,
              Pattern: '^[a-z0-9-_]+$'
            },
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            constraints: {
              MaxLength: 128
            },
            type: {
              name: 'String'
            }
          },
          userData: {
            required: false,
            serializedName: 'userData',
            constraints: {
              MaxLength: 16384
            },
            type: {
              name: 'String'
            }
          },
          persistedFaces: {
            required: false,
            serializedName: 'persistedFaces',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'PersonFaceResultElementType',
                  type: {
                    name: 'Composite',
                    className: 'PersonFaceResult'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = GetFaceListResult;
