/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The properties of the reservation recommendation.
 *
 */
class ReservationRecommendationPropertiesWithAmount {
  /**
   * Create a ReservationRecommendationPropertiesWithAmount.
   * @member {string} [lookBackPeriod] The number of days of usage to look back
   * for recommendation.
   * @member {uuid} [meterId] The meter id (GUID)
   * @member {string} [skuName] Sku name of the reserved instance resource.
   * @member {string} [region] Region of the reserved instance resource.
   * @member {string} [term] RI recommendations in one or three year terms.
   * @member {number} [costWithNoRI] The total amount of cost without reserved
   * instances.
   * @member {number} [recommendedQuantity] Recommended quality for reserved
   * instances.
   * @member {number} [totalCostWithRI] The total amount of cost with reserved
   * instances.
   * @member {number} [netSavings] Total estimated savings with reserved
   * instances.
   * @member {date} [firstUsageDate] The usage date for looking back.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ReservationRecommendationPropertiesWithAmount
   *
   * @returns {object} metadata of ReservationRecommendationPropertiesWithAmount
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ReservationRecommendationPropertiesWithAmount',
      type: {
        name: 'Composite',
        className: 'ReservationRecommendationPropertiesWithAmount',
        modelProperties: {
          lookBackPeriod: {
            required: false,
            readOnly: true,
            serializedName: 'lookBackPeriod',
            type: {
              name: 'String'
            }
          },
          meterId: {
            required: false,
            readOnly: true,
            serializedName: 'meterId',
            type: {
              name: 'String'
            }
          },
          skuName: {
            required: false,
            readOnly: true,
            serializedName: 'skuName',
            type: {
              name: 'String'
            }
          },
          region: {
            required: false,
            readOnly: true,
            serializedName: 'region',
            type: {
              name: 'String'
            }
          },
          term: {
            required: false,
            readOnly: true,
            serializedName: 'term',
            type: {
              name: 'String'
            }
          },
          costWithNoRI: {
            required: false,
            readOnly: true,
            serializedName: 'costWithNoRI',
            type: {
              name: 'Number'
            }
          },
          recommendedQuantity: {
            required: false,
            readOnly: true,
            serializedName: 'recommendedQuantity',
            type: {
              name: 'Number'
            }
          },
          totalCostWithRI: {
            required: false,
            readOnly: true,
            serializedName: 'totalCostWithRI',
            type: {
              name: 'Number'
            }
          },
          netSavings: {
            required: false,
            readOnly: true,
            serializedName: 'netSavings',
            type: {
              name: 'Number'
            }
          },
          firstUsageDate: {
            required: false,
            readOnly: true,
            serializedName: 'firstUsageDate',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = ReservationRecommendationPropertiesWithAmount;
