var executeCmds = require('./executeCmds.js');
var cmds = [
  { cmd: 'npm install', path: 'lib/common/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/legacyStorage' },
  { cmd: 'npm install', path: 'lib/services/legacyStorage' },
  { cmd: 'npm link ../../common/', path: 'lib/services/computeManagement/' },
  { cmd: 'npm install', path: 'lib/services/computeManagement/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/computeManagement2/' },
  { cmd: 'npm install', path: 'lib/services/computeManagement2/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/dnsManagement/' },
  { cmd: 'npm install', path: 'lib/services/dnsManagement/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/trafficManagerManagement/' },
  { cmd: 'npm install', path: 'lib/services/trafficManagerManagement/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/management/' },
  { cmd: 'npm install', path: 'lib/services/management/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/networkManagement/' },
  { cmd: 'npm install', path: 'lib/services/networkManagement/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/networkManagement2/' },
  { cmd: 'npm install', path: 'lib/services/networkManagement2/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/monitoring/' },
  { cmd: 'npm install', path: 'lib/services/monitoring/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/scheduler/' },
  { cmd: 'npm install', path: 'lib/services/scheduler/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/schedulerManagement/' },
  { cmd: 'npm install', path: 'lib/services/schedulerManagement/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/serviceBusManagement/' },
  { cmd: 'npm install', path: 'lib/services/serviceBusManagement/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/sqlManagement/' },
  { cmd: 'npm install', path: 'lib/services/sqlManagement/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/storageManagement/' },
  { cmd: 'npm install', path: 'lib/services/storageManagement/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/storageManagement2/' },
  { cmd: 'npm install', path: 'lib/services/storageManagement2/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/storeManagement/' },
  { cmd: 'npm install', path: 'lib/services/storeManagement/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/subscriptionManagement/' },
  { cmd: 'npm install', path: 'lib/services/subscriptionManagement/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/webSiteManagement/' },
  { cmd: 'npm install', path: 'lib/services/webSiteManagement/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/resourceManagement/' },
  { cmd: 'npm install', path: 'lib/services/resourceManagement/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/gallery/' },
  { cmd: 'npm install', path: 'lib/services/gallery/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/authorizationManagement/' },
  { cmd: 'npm install', path: 'lib/services/authorizationManagement/' },  
  { cmd: 'npm link ../../common/', path: 'lib/services/extra/' },
  { cmd: 'npm install', path: 'lib/services/extra/' },    
  { cmd: 'npm link ../../common/', path: 'lib/services/webSiteManagement2/' },
  { cmd: 'npm install', path: 'lib/services/webSiteManagement2/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/hdinsight/' },
  { cmd: 'npm install', path: 'lib/services/hdinsight/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/serviceBus/' },
  { cmd: 'npm install', path: 'lib/services/serviceBus/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/insights/' },
  { cmd: 'npm install', path: 'lib/services/insights/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/keyVault/' },
  { cmd: 'npm install', path: 'lib/services/keyVault/' },
  { cmd: 'npm link ../../common/', path: 'lib/services/keyVaultManagement/' },
  { cmd: 'npm install', path: 'lib/services/keyVaultManagement/' },
  { cmd: 'npm link lib/common/' },
  { cmd: 'npm link lib/services/legacyStorage' },
  { cmd: 'npm link lib/services/computeManagement/' },
  { cmd: 'npm link lib/services/computeManagement2/' },
  { cmd: 'npm link lib/services/dnsManagement/' },
  { cmd: 'npm link lib/services/trafficManagerManagement/' },
  { cmd: 'npm link lib/services/management/' },
  { cmd: 'npm link lib/services/networkManagement/' },
  { cmd: 'npm link lib/services/networkManagement2/' },
  { cmd: 'npm link lib/services/monitoring/' },
  { cmd: 'npm link lib/services/scheduler/' },
  { cmd: 'npm link lib/services/schedulerManagement/' },
  { cmd: 'npm link lib/services/serviceBusManagement/' },
  { cmd: 'npm link lib/services/sqlManagement/' },
  { cmd: 'npm link lib/services/storageManagement/' },
  { cmd: 'npm link lib/services/storageManagement2/' },
  { cmd: 'npm link lib/services/storeManagement/' },
  { cmd: 'npm link lib/services/subscriptionManagement/' },
  { cmd: 'npm link lib/services/webSiteManagement/' },
  { cmd: 'npm link lib/services/resourceManagement/' },
  { cmd: 'npm link lib/services/gallery/' },
  { cmd: 'npm link lib/services/webSiteManagement2/' },
  { cmd: 'npm link lib/services/hdinsight/' },
  { cmd: 'npm link lib/services/serviceBus/' },
  { cmd: 'npm link lib/services/keyVault/' },
  { cmd: 'npm link lib/services/keyVaultManagement/' },
  { cmd: 'npm link lib/services/insights/' },
  { cmd: 'npm link lib/services/authorizationManagement/' },
  { cmd: 'npm link lib/services/extra/' }
];

executeCmds.execute(cmds);