/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

var msRestAzure = require('ms-rest-azure');

exports.BaseResource = msRestAzure.BaseResource;
exports.CloudError = msRestAzure.CloudError;
exports.Resource = require('./resource');
exports.Display = require('./display');
exports.Operation = require('./operation');
exports.OsDiskImage = require('./osDiskImage');
exports.DataDiskImage = require('./dataDiskImage');
exports.ExtendedProduct = require('./extendedProduct');
exports.VirtualMachineExtensionProductProperties = require('./virtualMachineExtensionProductProperties');
exports.VirtualMachineProductProperties = require('./virtualMachineProductProperties');
exports.IconUris = require('./iconUris');
exports.ProductLink = require('./productLink');
exports.ProductProperties = require('./productProperties');
exports.Product = require('./product');
exports.Registration = require('./registration');
exports.ActivationKeyResult = require('./activationKeyResult');
exports.RegistrationParameter = require('./registrationParameter');
exports.CustomerSubscription = require('./customerSubscription');
exports.OperationList = require('./operationList');
exports.ProductList = require('./productList');
exports.RegistrationList = require('./registrationList');
exports.CustomerSubscriptionList = require('./customerSubscriptionList');
