/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a TrustedExternalTenant.
 */
class TrustedExternalTenant {
  /**
   * Create a TrustedExternalTenant.
   * @property {string} [value] GUID representing an external tenant.
   */
  constructor() {
  }

  /**
   * Defines the metadata of TrustedExternalTenant
   *
   * @returns {object} metadata of TrustedExternalTenant
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'TrustedExternalTenant',
      type: {
        name: 'Composite',
        className: 'TrustedExternalTenant',
        modelProperties: {
          value: {
            required: false,
            serializedName: 'value',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = TrustedExternalTenant;
