/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 * 
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the BootDiagnostics class.
 * @constructor
 * Describes Boot Diagnostics.
 * @member {boolean} [enabled] Gets or sets whether boot diagnostics should be
 * enabled on the Virtual Machine.
 * 
 * @member {string} [storageUri] Gets or sets the boot diagnostics storage
 * Uri. It should be a valid Uri
 * 
 */
function BootDiagnostics() {
}

/**
 * Defines the metadata of BootDiagnostics
 *
 * @returns {object} metadata of BootDiagnostics
 *
 */
BootDiagnostics.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'BootDiagnostics',
    type: {
      name: 'Composite',
      className: 'BootDiagnostics',
      modelProperties: {
        enabled: {
          required: false,
          serializedName: 'enabled',
          type: {
            name: 'Boolean'
          }
        },
        storageUri: {
          required: false,
          serializedName: 'storageUri',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = BootDiagnostics;
